# -*- coding: utf-8 -*-
"""Tests for PostProcessor command generation and edge cases.

This module tests the actual FFmpeg commands generated by PostProcessor methods,
input validation, and edge cases like special characters in filenames.
"""

import subprocess
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

from post_processor import PostProcessor


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def pp(tmp_path):
    """PostProcessor with FFmpeg path mocked."""
    with patch("shutil.which", return_value="/usr/bin/ffmpeg"):
        processor = PostProcessor(output_dir=str(tmp_path))
    return processor


@pytest.fixture
def mock_popen():
    """Mock subprocess.Popen for capturing FFmpeg commands."""
    with patch("subprocess.Popen") as mock:
        mock_process = MagicMock()
        mock_process.returncode = 0
        mock_process.communicate.return_value = (b"", b"")
        mock.return_value = mock_process
        yield mock


# ---------------------------------------------------------------------------
# Command Generation Tests - extract_audio
# ---------------------------------------------------------------------------

class TestExtractAudioCommands:
    """Verify ffmpeg commands for audio extraction."""

    def test_extract_audio_mp3_command(self, pp, mock_popen):
        """MP3 extraction uses libmp3lame codec and -vn flag."""
        pp.extract_audio("/tmp/video.mp4", format="mp3")

        args = mock_popen.call_args[0][0]
        assert args[0] == "/usr/bin/ffmpeg"
        assert "-i" in args
        assert "/tmp/video.mp4" in args
        assert "-vn" in args  # No video
        assert "-acodec" in args
        assert "libmp3lame" in args

    def test_extract_audio_aac_command(self, pp, mock_popen):
        """AAC extraction uses aac codec."""
        pp.extract_audio("/tmp/video.mp4", format="m4a")

        args = mock_popen.call_args[0][0]
        assert "-acodec" in args
        assert "aac" in args
        # Output should have .m4a extension
        output_path = args[-1]
        assert output_path.endswith(".m4a")

    def test_extract_audio_wav_command(self, pp, mock_popen):
        """WAV extraction uses pcm_s16le codec."""
        pp.extract_audio("/tmp/video.mp4", format="wav")

        args = mock_popen.call_args[0][0]
        assert "pcm_s16le" in args
        output_path = args[-1]
        assert output_path.endswith(".wav")

    def test_extract_audio_opus_command(self, pp, mock_popen):
        """Opus extraction uses libopus codec."""
        pp.extract_audio("/tmp/video.mp4", format="opus")

        args = mock_popen.call_args[0][0]
        assert "libopus" in args
        output_path = args[-1]
        assert output_path.endswith(".opus")

    def test_extract_audio_default_format(self, pp, mock_popen):
        """Default format is MP3."""
        pp.extract_audio("/tmp/video.mp4")

        args = mock_popen.call_args[0][0]
        assert "libmp3lame" in args

    def test_extract_audio_unknown_format_defaults_mp3(self, pp, mock_popen):
        """Unknown format falls back to MP3."""
        pp.extract_audio("/tmp/video.mp4", format="unknown")

        args = mock_popen.call_args[0][0]
        assert "libmp3lame" in args


# ---------------------------------------------------------------------------
# Command Generation Tests - normalize_video (normalize_audio)
# ---------------------------------------------------------------------------

class TestNormalizeAudioCommands:
    """Verify ffmpeg commands for audio normalization."""

    def test_normalize_audio_uses_loudnorm(self, pp, mock_popen):
        """Audio normalization uses loudnorm filter with correct parameters."""
        pp.normalize_audio("/tmp/video.mp4")

        args = mock_popen.call_args[0][0]
        assert "-af" in args
        af_idx = args.index("-af")
        filter_str = args[af_idx + 1]
        assert "loudnorm" in filter_str
        assert "I=-16" in filter_str
        assert "TP=-1.5" in filter_str
        assert "LRA=11" in filter_str

    def test_normalize_audio_copies_video(self, pp, mock_popen):
        """Audio normalization copies video stream without re-encoding."""
        pp.normalize_audio("/tmp/video.mp4")

        args = mock_popen.call_args[0][0]
        assert "-c:v" in args
        cv_idx = args.index("-c:v")
        assert args[cv_idx + 1] == "copy"


# ---------------------------------------------------------------------------
# Command Generation Tests - change_speed
# ---------------------------------------------------------------------------

class TestChangeSpeedCommands:
    """Verify ffmpeg commands for speed changes."""

    def test_change_speed_double_setpts(self, pp, mock_popen):
        """2x speed uses setpts=0.5*PTS for video."""
        pp.change_speed("/tmp/video.mp4", speed=2.0)

        args = mock_popen.call_args[0][0]
        assert "-vf" in args
        vf_idx = args.index("-vf")
        video_filter = args[vf_idx + 1]
        assert "setpts=" in video_filter
        assert "0.5" in video_filter

    def test_change_speed_half_setpts(self, pp, mock_popen):
        """0.5x speed uses setpts=2.0*PTS for video."""
        pp.change_speed("/tmp/video.mp4", speed=0.5)

        args = mock_popen.call_args[0][0]
        vf_idx = args.index("-vf")
        video_filter = args[vf_idx + 1]
        assert "2.0" in video_filter

    def test_change_speed_audio_atempo(self, pp, mock_popen):
        """Speed change includes atempo filter for audio."""
        pp.change_speed("/tmp/video.mp4", speed=1.5)

        args = mock_popen.call_args[0][0]
        assert "-af" in args
        af_idx = args.index("-af")
        audio_filter = args[af_idx + 1]
        assert "atempo=" in audio_filter

    def test_change_speed_3x_chains_atempo(self, pp, mock_popen):
        """Speed > 2x chains atempo filters (atempo max is 2.0)."""
        pp.change_speed("/tmp/video.mp4", speed=3.0)

        args = mock_popen.call_args[0][0]
        af_idx = args.index("-af")
        audio_filter = args[af_idx + 1]
        # Should have atempo=2.0 plus another atempo for remaining 1.5
        assert "atempo=2.0" in audio_filter
        assert audio_filter.count("atempo") >= 2

    def test_change_speed_output_filename(self, pp, mock_popen):
        """Output filename includes speed multiplier."""
        pp.change_speed("/tmp/video.mp4", speed=1.5)

        args = mock_popen.call_args[0][0]
        output_path = args[-1]
        assert "speed_1.5x" in output_path


# ---------------------------------------------------------------------------
# Command Generation Tests - trim
# ---------------------------------------------------------------------------

class TestTrimCommands:
    """Verify ffmpeg commands for video trimming."""

    def test_trim_uses_ss_and_to(self, pp, mock_popen):
        """Trim uses -ss for start and -to for end time."""
        pp.trim("/tmp/video.mp4", start_time="00:01:00", end_time="00:02:30")

        args = mock_popen.call_args[0][0]
        assert "-ss" in args
        assert "-to" in args
        ss_idx = args.index("-ss")
        to_idx = args.index("-to")
        assert args[ss_idx + 1] == "00:01:00"
        assert args[to_idx + 1] == "00:02:30"

    def test_trim_uses_stream_copy(self, pp, mock_popen):
        """Trim uses stream copy for fast operation."""
        pp.trim("/tmp/video.mp4", start_time="00:00:10", end_time="00:00:30")

        args = mock_popen.call_args[0][0]
        assert "-c" in args
        c_idx = args.index("-c")
        assert args[c_idx + 1] == "copy"

    def test_trim_output_filename(self, pp, mock_popen):
        """Output filename includes 'trimmed' suffix."""
        pp.trim("/tmp/video.mp4", start_time="00:00:00", end_time="00:00:10")

        args = mock_popen.call_args[0][0]
        output_path = args[-1]
        assert "trimmed" in output_path

    def test_trim_overwrite_flag(self, pp, mock_popen):
        """Trim command includes -y for overwrite."""
        pp.trim("/tmp/video.mp4", start_time="00:00:00", end_time="00:00:05")

        args = mock_popen.call_args[0][0]
        assert "-y" in args


# ---------------------------------------------------------------------------
# Command Generation Tests - compress
# ---------------------------------------------------------------------------

class TestCompressCommands:
    """Verify ffmpeg commands for video compression."""

    def test_compress_uses_h264(self, pp, mock_popen):
        """Compression uses libx264 codec."""
        pp.compress("/tmp/video.mp4", crf=28)

        args = mock_popen.call_args[0][0]
        assert "-c:v" in args
        cv_idx = args.index("-c:v")
        assert args[cv_idx + 1] == "libx264"

    def test_compress_crf_value(self, pp, mock_popen):
        """Compression uses specified CRF value."""
        pp.compress("/tmp/video.mp4", crf=23)

        args = mock_popen.call_args[0][0]
        assert "-crf" in args
        crf_idx = args.index("-crf")
        assert args[crf_idx + 1] == "23"

    def test_compress_audio_aac(self, pp, mock_popen):
        """Compression re-encodes audio to AAC at 128k."""
        pp.compress("/tmp/video.mp4")

        args = mock_popen.call_args[0][0]
        assert "-c:a" in args
        assert "aac" in args
        assert "-b:a" in args
        assert "128k" in args


# ---------------------------------------------------------------------------
# Command Generation Tests - scale and upscale
# ---------------------------------------------------------------------------

class TestScaleCommands:
    """Verify ffmpeg commands for scaling operations."""

    def test_scale_specific_resolution(self, pp, mock_popen):
        """Scale to specific width x height."""
        pp.scale("/tmp/video.mp4", width=1280, height=720)

        args = mock_popen.call_args[0][0]
        assert "-vf" in args
        vf_idx = args.index("-vf")
        filter_str = args[vf_idx + 1]
        assert "scale=1280:720" in filter_str
        assert "force_original_aspect_ratio=decrease" in filter_str
        assert "pad=1280:720" in filter_str

    def test_upscale_to_1080p(self, pp, mock_popen):
        """Upscale uses lanczos algorithm and maintains aspect ratio."""
        pp.upscale("/tmp/video.mp4", target_height=1080)

        args = mock_popen.call_args[0][0]
        assert "-vf" in args
        vf_idx = args.index("-vf")
        filter_str = args[vf_idx + 1]
        assert "scale=-2:1080" in filter_str
        assert "lanczos" in filter_str

    def test_upscale_output_filename(self, pp, mock_popen):
        """Upscale output includes resolution in filename."""
        pp.upscale("/tmp/video.mp4", target_height=720)

        args = mock_popen.call_args[0][0]
        output_path = args[-1]
        assert "720p" in output_path


# ---------------------------------------------------------------------------
# Command Generation Tests - denoise
# ---------------------------------------------------------------------------

class TestDenoiseCommands:
    """Verify ffmpeg commands for video denoising."""

    def test_denoise_uses_hqdn3d(self, pp, mock_popen):
        """Denoise uses hqdn3d filter."""
        pp.denoise_video("/tmp/video.mp4")

        args = mock_popen.call_args[0][0]
        assert "-vf" in args
        vf_idx = args.index("-vf")
        filter_str = args[vf_idx + 1]
        assert "hqdn3d" in filter_str

    def test_denoise_copies_audio(self, pp, mock_popen):
        """Denoise copies audio stream."""
        pp.denoise_video("/tmp/video.mp4")

        args = mock_popen.call_args[0][0]
        assert "-c:a" in args
        ca_idx = args.index("-c:a")
        assert args[ca_idx + 1] == "copy"


# ---------------------------------------------------------------------------
# Input Validation Tests
# ---------------------------------------------------------------------------

class TestInputValidation:
    """Test input validation for various methods."""

    def test_change_speed_zero_invalid(self, pp):
        """Speed of 0 returns None without calling FFmpeg."""
        with patch.object(pp, "_run_ffmpeg") as mock_ff:
            result = pp.change_speed("/tmp/video.mp4", speed=0)
        assert result is None
        mock_ff.assert_not_called()

    def test_change_speed_negative_invalid(self, pp):
        """Negative speed returns None without calling FFmpeg."""
        with patch.object(pp, "_run_ffmpeg") as mock_ff:
            result = pp.change_speed("/tmp/video.mp4", speed=-2)
        assert result is None
        mock_ff.assert_not_called()

    def test_change_speed_over_4_invalid(self, pp):
        """Speed > 4 returns None without calling FFmpeg."""
        with patch.object(pp, "_run_ffmpeg") as mock_ff:
            result = pp.change_speed("/tmp/video.mp4", speed=5)
        assert result is None
        mock_ff.assert_not_called()

    def test_change_speed_exactly_4_valid(self, pp, mock_popen):
        """Speed of exactly 4 is valid."""
        result = pp.change_speed("/tmp/video.mp4", speed=4.0)
        assert result is not None
        mock_popen.assert_called()

    def test_change_speed_very_slow_valid(self, pp, mock_popen):
        """Very slow speed (0.1) is valid."""
        result = pp.change_speed("/tmp/video.mp4", speed=0.1)
        assert result is not None


# ---------------------------------------------------------------------------
# Edge Cases - Special Characters
# ---------------------------------------------------------------------------

class TestSpecialCharacterPaths:
    """Test handling of special characters in file paths."""

    def test_path_with_spaces(self, pp, mock_popen, tmp_path):
        """Paths with spaces are handled correctly."""
        input_path = str(tmp_path / "my video file.mp4")
        pp.extract_audio(input_path, format="mp3")

        args = mock_popen.call_args[0][0]
        assert input_path in args

    def test_path_with_unicode(self, pp, mock_popen, tmp_path):
        """Unicode filenames are handled correctly."""
        input_path = str(tmp_path / "видео_файл.mp4")
        pp.extract_audio(input_path, format="mp3")

        args = mock_popen.call_args[0][0]
        assert input_path in args

    def test_path_with_special_chars(self, pp, mock_popen, tmp_path):
        """Filenames with special characters are handled."""
        input_path = str(tmp_path / "video (1) [final].mp4")
        pp.trim(input_path, "00:00:00", "00:00:10")

        args = mock_popen.call_args[0][0]
        assert input_path in args

    def test_path_with_ampersand(self, pp, mock_popen, tmp_path):
        """Filenames with ampersand are handled."""
        input_path = str(tmp_path / "tom & jerry.mp4")
        pp.compress(input_path)

        args = mock_popen.call_args[0][0]
        assert input_path in args


# ---------------------------------------------------------------------------
# Edge Cases - Duration
# ---------------------------------------------------------------------------

class TestDurationEdgeCases:
    """Test edge cases for video duration."""

    def test_trim_very_short_video(self, pp, mock_popen):
        """Trimming sub-second duration."""
        pp.trim("/tmp/video.mp4", start_time="00:00:00.000", end_time="00:00:00.500")

        args = mock_popen.call_args[0][0]
        ss_idx = args.index("-ss")
        to_idx = args.index("-to")
        assert args[ss_idx + 1] == "00:00:00.000"
        assert args[to_idx + 1] == "00:00:00.500"

    def test_trim_24_hour_video(self, pp, mock_popen):
        """Trimming videos longer than 24 hours."""
        pp.trim("/tmp/long_video.mp4", start_time="23:59:00", end_time="25:00:00")

        args = mock_popen.call_args[0][0]
        ss_idx = args.index("-ss")
        to_idx = args.index("-to")
        assert args[ss_idx + 1] == "23:59:00"
        assert args[to_idx + 1] == "25:00:00"

    def test_trim_seconds_format(self, pp, mock_popen):
        """Trim accepts time in seconds format."""
        pp.trim("/tmp/video.mp4", start_time="10", end_time="20")

        args = mock_popen.call_args[0][0]
        ss_idx = args.index("-ss")
        to_idx = args.index("-to")
        assert args[ss_idx + 1] == "10"
        assert args[to_idx + 1] == "20"


# ---------------------------------------------------------------------------
# FFmpeg Execution Tests
# ---------------------------------------------------------------------------

class TestFFmpegExecution:
    """Test FFmpeg execution behavior."""

    def test_ffmpeg_failure_returns_none(self, pp):
        """Failed FFmpeg execution returns None."""
        with patch("subprocess.Popen") as mock_popen:
            mock_process = MagicMock()
            mock_process.returncode = 1
            mock_process.communicate.return_value = (b"", b"Error occurred")
            mock_popen.return_value = mock_process

            result = pp.extract_audio("/tmp/video.mp4")
        assert result is None

    def test_ffmpeg_exception_returns_none(self, pp):
        """FFmpeg exception returns None and doesn't crash."""
        with patch("subprocess.Popen") as mock_popen:
            mock_popen.side_effect = OSError("FFmpeg not found")

            result = pp.extract_audio("/tmp/video.mp4")
        assert result is None

    def test_callback_called_on_success(self, pp, mock_popen):
        """Callback is invoked with True on success."""
        callback = MagicMock()
        pp.extract_audio("/tmp/video.mp4", callback=callback)

        callback.assert_called_once_with(True)

    def test_callback_called_on_failure(self, pp):
        """Callback is invoked with False on failure."""
        with patch("subprocess.Popen") as mock_popen:
            mock_process = MagicMock()
            mock_process.returncode = 1
            mock_process.communicate.return_value = (b"", b"Error")
            mock_popen.return_value = mock_process

            callback = MagicMock()
            pp.extract_audio("/tmp/video.mp4", callback=callback)

        callback.assert_called_once_with(False)

    def test_overwrite_flag_present(self, pp, mock_popen):
        """All operations include -y for overwrite without prompting."""
        pp.compress("/tmp/video.mp4")
        args = mock_popen.call_args[0][0]
        assert "-y" in args

        mock_popen.reset_mock()
        pp.denoise_video("/tmp/video.mp4")
        args = mock_popen.call_args[0][0]
        assert "-y" in args


# ---------------------------------------------------------------------------
# Media Info Tests
# ---------------------------------------------------------------------------

class TestGetMediaInfo:
    """Test media info retrieval via ffprobe."""

    def test_get_media_info_success(self, pp):
        """Successful ffprobe returns parsed JSON."""
        mock_output = '{"format": {"filename": "test.mp4"}, "streams": []}'
        with patch("subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(
                returncode=0,
                stdout=mock_output
            )
            result = pp.get_media_info("/tmp/test.mp4")

        assert result == {"format": {"filename": "test.mp4"}, "streams": []}

    def test_get_media_info_failure_returns_empty(self, pp):
        """Failed ffprobe returns empty dict."""
        with patch("subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(returncode=1, stdout="")
            result = pp.get_media_info("/tmp/test.mp4")

        assert result == {}

    def test_get_media_info_exception_returns_empty(self, pp):
        """ffprobe exception returns empty dict."""
        with patch("subprocess.run") as mock_run:
            mock_run.side_effect = subprocess.TimeoutExpired("ffprobe", 30)
            result = pp.get_media_info("/tmp/test.mp4")

        assert result == {}
